theme: jekyll-theme-minimal
logo: https://hips.hearstapps.com/hmg-prod/images/mh-steve-stranger-things-legend-1561499047-1-1561561628.jpg?crop=0.888888888888889xw:1xh;center,top&resize=1200:*
title: Bioinformatics
